import { Pause, Play, RotateCcw, Square, Terminal } from "lucide-react";

import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../../components/ui/card";
import { executionLogs, executionQueue } from "../../mock/rpaMultiPageMock";

type BadgeTone = "blue" | "green" | "orange" | "red" | "slate";

function statusTone(status: string): BadgeTone {
  if (status === "失败") return "red";
  if (status === "成功") return "green";
  if (status === "运行中") return "blue";
  return "orange";
}

export function ExecutorPage() {
  return (
    <div className="grid grid-cols-1 gap-4 2xl:grid-cols-[320px_minmax(0,1fr)_420px]">
      <Card><CardHeader><CardTitle>任务配置</CardTitle><Button size="sm">保存为模板</Button></CardHeader><CardContent className="space-y-4 text-sm"><section><div className="mb-2 font-semibold">1. 执行对象</div><div className="grid grid-cols-2 gap-2"><Button variant="primary">Workflow</Button><Button>Skill</Button></div><div className="mt-2 rounded-xl border border-slate-200 p-3">淘宝搜索商品流程<br/><span className="text-xs text-emerald-600">v1.2.3 · 已发布</span></div></section><section><div className="mb-2 font-semibold">2. Provider / Device</div><div className="rounded-xl border border-slate-200 p-3">android_adb <span className="float-right text-emerald-600">online</span><div className="text-xs text-slate-500">Mobile device bridge</div></div></section><section><div className="mb-2 font-semibold">3. 参数配置</div>{[["keyword","无线耳机"],["search_input","无线耳机"],["sort","综合"],["page_limit","2"]].map(([k,v])=><label key={k} className="mb-2 grid grid-cols-[100px_1fr] items-center gap-2"><span className="text-slate-500">{k}</span><input className="h-9 rounded-lg border border-slate-200 px-3" defaultValue={v}/></label>)}</section><section><div className="mb-2 font-semibold">4. 执行选项</div><div className="grid grid-cols-2 gap-2"><Button>Dry Run</Button><Button>指数退避</Button><Button>并发 1</Button><Button>超时 300s</Button></div></section><Button variant="primary" className="w-full"><Play className="h-4 w-4" />提交执行</Button></CardContent></Card>
      <div className="space-y-4"><Card><CardHeader><CardTitle>执行队列</CardTitle><Button variant="primary" size="sm">+ 新建执行</Button></CardHeader><CardContent><div className="mb-3 flex flex-wrap gap-2">{["全部 12","排队 3","运行中 2","成功 6","失败 1"].map((tab,index)=><Badge key={tab} tone={index===0?"blue":"slate"}>{tab}</Badge>)}</div><div className="overflow-x-auto rounded-xl border border-slate-100"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-3 py-3">优先级</th><th>任务/实例</th><th>状态</th><th>进度</th><th>预计耗时</th><th>提交时间</th></tr></thead><tbody className="divide-y divide-slate-100">{executionQueue.map((job)=><tr key={job.id}><td className="px-3 py-3"><Badge tone={job.priority==="P0"?"red":job.priority==="P1"?"orange":"blue"}>{job.priority}</Badge></td><td><div className="font-medium text-slate-900">{job.task}</div><div className="text-xs text-slate-500">{job.id}</div></td><td><Badge tone={statusTone(job.status)}>{job.status}</Badge></td><td>{job.progress}</td><td>{job.eta}</td><td>{job.submitted}</td></tr>)}</tbody></table></div></CardContent></Card><Card><CardHeader><CardTitle><Terminal className="mr-2 inline h-4 w-4" />执行日志</CardTitle><Button size="sm">下载日志</Button></CardHeader><CardContent><pre className="max-h-[280px] overflow-auto rounded-2xl bg-slate-950 p-4 text-xs leading-6 text-slate-100">{executionLogs.join("\n")}</pre></CardContent></Card></div>
      <div className="space-y-4"><Card><CardHeader><CardTitle>当前运行状态</CardTitle><Badge tone="blue">运行中</Badge></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-3 text-sm"><div><span className="text-slate-500">实例 ID</span><b className="block">a1b2c3d4</b></div><div><span className="text-slate-500">运行时长</span><b className="block">00:00:48</b></div></div><div><div className="mb-1 flex justify-between text-sm"><span>总体进度</span><b>45%</b></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 w-[45%] rounded-full bg-blue-600" /></div></div><div className="rounded-xl border border-slate-100 p-3 text-sm"><b>android-0014</b><div className="text-xs text-slate-500">Android 13 · 1080x2340 · 76%</div></div><div className="rounded-xl bg-blue-50 p-3 text-sm"><Badge tone="blue">Step 03</Badge> Action Inspector · tap search field</div><div className="grid grid-cols-5 gap-2">{Array.from({length:5}).map((_,i)=><div key={i} className={`h-20 rounded-lg ${i===2?"ring-2 ring-blue-500":"ring-1 ring-slate-200"} bg-gradient-to-b from-white to-slate-100`} />)}</div><div className="grid grid-cols-3 gap-2"><Button><Pause className="h-4 w-4" />暂停</Button><Button variant="danger"><Square className="h-4 w-4" />停止</Button><Button><RotateCcw className="h-4 w-4" />重试</Button></div></CardContent></Card><Card><CardHeader><CardTitle>失败恢复策略</CardTitle></CardHeader><CardContent className="space-y-2 text-sm">{["从当前步骤重试","从上一步重试","跳过当前步骤","终止并标记失败"].map((item)=><div key={item} className="rounded-xl border border-slate-100 p-3">{item}</div>)}</CardContent></Card></div>
    </div>
  );
}
