import { Brain, Download, Pin, Search, Trash2 } from "lucide-react";

import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../../components/ui/card";
import { memoryCategories, memoryItems } from "../../mock/rpaMultiPageMock";

export function MemoryCenterPage() {
  return (
    <div className="space-y-4">
      <section className="grid grid-cols-1 gap-4 2xl:grid-cols-[260px_minmax(0,1fr)_420px]">
        <Card><CardHeader><CardTitle>记忆分类</CardTitle></CardHeader><CardContent className="space-y-3">{memoryCategories.map((item,index)=><div key={item.name} className={`rounded-xl border p-3 ${index===0?"border-blue-200 bg-blue-50":"border-slate-100"}`}><div className="flex items-center justify-between"><b>{item.name}</b><Badge tone={index===0?"blue":"slate"}>{item.count}</Badge></div><div className="mt-1 text-xs text-slate-500">{item.desc}</div></div>)}<div className="rounded-2xl border border-slate-100 p-4"><div className="flex items-center gap-3"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-emerald-50 text-emerald-700 ring-8 ring-emerald-100"><Brain className="h-6 w-6" /></div><div><b>3,265</b><div className="text-xs text-slate-500">Total Memories</div></div></div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-2 w-[62%] rounded-full bg-emerald-500" /></div></div></CardContent></Card>
        <Card><CardHeader><div><CardTitle>记忆列表</CardTitle><div className="mt-1 text-xs text-slate-500">1,248 memories</div></div></CardHeader><CardContent><div className="mb-3 flex h-10 items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm text-slate-400"><Search className="h-4 w-4" />搜索记忆内容、标签、来源...</div><div className="mb-3 flex flex-wrap gap-2">{["类型","相关度","新鲜度","关联 Provider","压缩状态","重置"].map((filter)=><Button key={filter} size="sm">{filter}</Button>)}</div><div className="overflow-x-auto rounded-xl border border-slate-100"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-3 py-3">Memory</th><th>Relevance</th><th>Freshness</th><th>Type</th><th>Provider</th><th>Compression</th></tr></thead><tbody className="divide-y divide-slate-100">{memoryItems.map((item,index)=><tr key={item.title} className={index===1?"bg-blue-50/50":""}><td className="px-3 py-3"><b>{item.title}</b><div className="text-xs text-slate-500">沉淀为可检索经验与执行策略...</div></td><td><span className="font-semibold text-emerald-600">{item.relevance}</span></td><td>{item.fresh}</td><td><Badge tone={item.type==="Recovery"?"orange":item.type==="Skill"?"blue":"green"}>{item.type}</Badge></td><td>android_adb</td><td>{item.compression}</td></tr>)}</tbody></table></div></CardContent></Card>
        <Card><CardHeader><CardTitle>记忆详情</CardTitle><Badge tone="orange">Pinned</Badge></CardHeader><CardContent className="space-y-4 text-sm"><section><h3 className="text-lg font-semibold text-slate-950">搜索商品流程 - 结果页加载等待策略</h3><p className="mt-2 text-slate-500">总结在淘宝搜索结果页中，如何稳定判断结果加载完成。对比元素存在、列表数量稳定、关键元素可见、网络空闲，并给出优先级建议。</p></section><section><div className="mb-2 font-semibold">Tags</div><div className="flex flex-wrap gap-2">{["等待策略","结果页","加载完成","列表","稳定性"].map((tag)=><Badge key={tag}>{tag}</Badge>)}</div></section><section><div className="mb-2 font-semibold">Embedding / Metadata</div><div className="grid grid-cols-2 gap-2 text-xs">{["Relevance 0.92","Freshness 6h ago","Type Workflow","Provider android_adb","Dim 1536","Tokens 912","Compression 60%","Source Traces 12"].map((meta)=><span key={meta} className="rounded-lg bg-slate-100 px-2 py-1">{meta}</span>)}</div></section><section><div className="mb-2 font-semibold">Related Assets</div><div className="grid grid-cols-2 gap-2 text-xs">{["trc_a1b2c3d4","wf_search_product_v2","skill_wait_list_stable","exp_slow_network_wait"].map((asset)=><span key={asset} className="rounded-lg border border-slate-100 p-2">{asset}</span>)}</div></section><div className="flex flex-wrap gap-2"><Button variant="primary">Compress</Button><Button variant="danger"><Trash2 className="h-4 w-4" />Forget</Button><Button><Download className="h-4 w-4" />Export</Button><Button><Pin className="h-4 w-4" />Pin</Button></div></CardContent></Card>
      </section>
      <Card><CardHeader><CardTitle>Trace / Workflow / Skill 关联图</CardTitle><div className="flex gap-2"><Badge>Graph View</Badge><Badge>深度 2</Badge></div></CardHeader><CardContent><div className="relative min-h-[260px] overflow-hidden rounded-2xl border border-slate-100 bg-slate-50 p-6"><div className="mx-auto flex h-full max-w-5xl items-center justify-center"><div className="grid grid-cols-3 gap-8 text-center text-sm"><div className="space-y-3">{["结果页首次加载 Trace","慢网环境加载 Trace","无结果页 Trace"].map((node)=><div key={node} className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-emerald-800">{node}</div>)}</div><div className="flex items-center"><div className="rounded-2xl border-2 border-blue-300 bg-blue-50 p-5 font-semibold text-blue-800">搜索商品流程 - 结果页加载等待策略<br/><span className="text-xs">Workflow Memory</span></div></div><div className="space-y-3">{["淘宝搜索商品流程 v2","列表加载完成等待 Skill","高成功率：商品筛选策略"].map((node)=><div key={node} className="rounded-xl border border-blue-200 bg-white p-3 text-blue-800">{node}</div>)}</div></div></div></div></CardContent></Card>
    </div>
  );
}
