import { AlertCircle, Camera, Play, Search } from "lucide-react";

import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../../components/ui/card";
import { traceList, traceReplaySteps } from "../../mock/rpaMultiPageMock";

type BadgeTone = "blue" | "green" | "orange" | "red" | "slate";

function tone(status: string): BadgeTone {
  return status === "failed" ? "red" : status === "success" ? "green" : status === "partial" || status === "skipped" ? "orange" : "blue";
}

export function TraceReplayPage() {
  return (
    <div className="grid grid-cols-1 gap-4 2xl:grid-cols-[300px_minmax(0,1fr)_360px]">
      <Card><CardHeader><CardTitle>Trace 搜索与过滤</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex h-10 items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm text-slate-400"><Search className="h-4 w-4" />搜索 task_id / workflow / step</div>{["task_id","workflow_id","provider","status","time range"].map((field)=><input key={field} className="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder={field}/>) }<div className="pt-2 text-sm text-slate-500">78 traces found</div>{traceList.map((item,index)=><div key={item.id} className={`rounded-xl border p-3 ${index===0?"border-blue-200 bg-blue-50":"border-slate-100"}`}><div className="flex items-center justify-between"><b className="text-slate-900">{item.id}</b><Badge tone={tone(item.status)}>{item.status}</Badge></div><div className="mt-1 text-xs text-slate-500">{item.workflow}</div><div className="text-xs text-slate-500">{item.note}</div></div>)}</CardContent></Card>
      <div className="space-y-4"><Card><CardHeader><div><CardTitle>task_20240522_0017 <Badge tone="red">failed</Badge></CardTitle><div className="mt-1 text-xs text-slate-500">workflow wf_taobao_search · provider android_adb · duration 00:02:18.732</div></div></CardHeader><CardContent><div className="space-y-3">{traceReplaySteps.map((step)=><div key={step.step} className={`grid grid-cols-[80px_36px_minmax(0,1fr)_90px] items-center gap-3 rounded-xl border p-3 ${step.status==="failed"?"border-red-200 bg-red-50":"border-slate-100"}`}><span className="text-xs text-slate-500">{step.time}</span><span className={`flex h-8 w-8 items-center justify-center rounded-full ${step.status==="failed"?"bg-red-100 text-red-700":"bg-emerald-100 text-emerald-700"}`}>{step.step}</span><div><b className="text-slate-900">{step.title}</b><div className="text-xs text-slate-500">{step.action}</div></div><Badge tone={tone(step.status)}>{step.status}</Badge></div>)}</div><div className="mt-5 flex items-center gap-3"><Button variant="primary" size="icon"><Play className="h-4 w-4" /></Button><div className="h-2 flex-1 rounded-full bg-slate-100"><div className="h-2 w-[31%] rounded-full bg-red-500" /></div><span className="text-sm text-slate-500">00:31.114 / 02:18.732</span></div></CardContent></Card><section className="grid grid-cols-1 gap-4 xl:grid-cols-3"><Card><CardHeader><CardTitle>截图查看</CardTitle></CardHeader><CardContent><div className="flex h-48 items-center justify-center rounded-2xl bg-gradient-to-br from-orange-50 to-blue-50 text-sm text-slate-500"><Camera className="mr-2 h-5 w-5" />tap_before.png</div></CardContent></Card><Card><CardHeader><CardTitle>结构化 JSON</CardTitle></CardHeader><CardContent><pre className="h-48 overflow-auto rounded-2xl bg-slate-950 p-3 text-xs text-slate-100">{`{\n  "stepId": "Step 04",\n  "action": "tap",\n  "target": "search_button",\n  "risk": "L2"\n}`}</pre></CardContent></Card><Card><CardHeader><CardTitle>错误详情</CardTitle></CardHeader><CardContent className="text-sm"><b>ELEMENT_NOT_FOUND</b><p className="mt-2 text-slate-500">LocatorResolutionError · id=search_button 不存在</p></CardContent></Card></section></div>
      <Card><CardHeader><CardTitle>Step Inspector</CardTitle><Badge tone="red">Step 04</Badge></CardHeader><CardContent className="space-y-4"><section><div className="mb-2 font-semibold">Action JSON</div><pre className="rounded-2xl bg-slate-950 p-3 text-xs text-slate-100">{`{\n "type":"tap",\n "target":"search_button",\n "coordinates":{"x":958,"y":1834}\n}`}</pre></section><section className="rounded-xl bg-red-50 p-3 text-sm text-red-700"><AlertCircle className="mb-2 h-4 w-4" />Safety Result: blocked · L2 manual confirm required</section><section><div className="font-semibold">失败原因分析</div><p className="mt-2 text-sm text-slate-500">当前页面结构已变更，元素 id 不存在，相似元素匹配度 0.42。</p></section><Button variant="primary" className="w-full">转为 Workflow</Button><Button className="w-full">生成修复建议</Button></CardContent></Card>
    </div>
  );
}
